{
 "title": "Concourse SLI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 3, "y": 0 },
   "content": "# Create and Run New Pipeline\n"
  },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 12, "y": 0 }, "content": "# View Build History" },
  {
   "title": "Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_create_and_run_new_pipeline[30d])*100"
    }
   ]
  },
  {
   "title": "Week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_create_and_run_new_pipeline[7d])*100"
    }
   ]
  },
  {
   "title": "Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_create_and_run_new_pipeline[1d])*100"
    }
   ]
  },
  {
   "title": "Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_view_build_history[30d])*100"
    }
   ]
  },
  {
   "title": "Week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_view_build_history[7d])*100"
    }
   ]
  },
  {
   "title": "Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_view_build_history[1d])*100"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_create_and_run_new_pipeline"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_create_and_run_new_pipeline"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 3, "y": 10 }, "content": "# View Public Pipeline\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 12, "y": 10 }, "content": "# Run Existing Pipeline\n" },
  {
   "title": "Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_view_public_pipeline[30d])*100"
    }
   ]
  },
  {
   "title": "Week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_view_public_pipeline[7d])*100"
    }
   ]
  },
  {
   "title": "Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_view_public_pipeline[1d])*100"
    }
   ]
  },
  {
   "title": "Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_run_existing_pipeline[30d])*100"
    }
   ]
  },
  {
   "title": "Week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_run_existing_pipeline[7d])*100"
    }
   ]
  },
  {
   "title": "Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_run_existing_pipeline[1d])*100"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_view_public_pipeline" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_run_existing_pipeline"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 3, "y": 20 }, "content": "# Hijack Failing Build" },
  {
   "title": "Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_fly_hijack_failing_build[30d])*100"
    }
   ]
  },
  {
   "title": "Week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_fly_hijack_failing_build[7d])*100"
    }
   ]
  },
  {
   "title": "Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(concourse_fly_hijack_failing_build[1d])*100"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_view_public_pipeline" }
   ]
  }
 ]
}